# Read Data Sample

In [1]:
import pandas as pd
import numpy as np
from collections import namedtuple
pd.set_option("display.max_rows",35)
%matplotlib inline

In [2]:
class dataset:
    kdd_train_2labels = pd.read_pickle("dataset/kdd_train_2labels.pkl")
    kdd_test_2labels = pd.read_pickle("dataset/kdd_test_2labels.pkl")
    
    kdd_train_5labels = pd.read_pickle("dataset/kdd_train_5labels.pkl")
    kdd_test_5labels = pd.read_pickle("dataset/kdd_test_5labels.pkl")
    

In [3]:
dataset.kdd_train_2labels.shape

(125973, 124)

In [4]:
dataset.kdd_test_2labels.shape

(22544, 124)

In [5]:
from sklearn import model_selection as ms
from sklearn import preprocessing as pp

class preprocess:
    
    output_columns_2labels = ['is_Attack','is_Normal']
    
    x_input = dataset.kdd_train_2labels.drop(output_columns_2labels, axis = 1)
    y_output = dataset.kdd_train_2labels.loc[:,output_columns_2labels]

    x_test_input = dataset.kdd_test_2labels.drop(output_columns_2labels, axis = 1)
    y_test = dataset.kdd_test_2labels.loc[:,output_columns_2labels]

    ss = pp.StandardScaler()

    x_train = ss.fit_transform(x_input)
    x_test = ss.transform(x_test_input)

    y_train = y_output.values
    y_test = y_test.values

preprocess.x_train.std()

0.99589320646770185

In [6]:
import tensorflow as tf
from tensorflow.contrib.legacy_seq2seq.python.ops.seq2seq import basic_rnn_seq2seq
from tensorflow.contrib.rnn import RNNCell, LSTMCell, MultiRNNCell


In [7]:
class network(object):
    
    input_dim = 122
    classes = 2
    hidden_encoder_dim = 122
    hidden_layers = 1
    latent_dim = 10

    hidden_decoder_dim = 122
    lam = 0.01
    
    def __init__(self, classes, hidden_layers, num_of_features):
        self.classes = classes
        self.hidden_layers = hidden_layers
        self.latent_dim = num_of_features
            
    def build_layers(self):
        tf.reset_default_graph()
        #learning_rate = tf.Variable(initial_value=0.001)

        input_dim = self.input_dim
        classes = self.classes
        hidden_encoder_dim = self.hidden_encoder_dim
        hidden_layers = self.hidden_layers
        latent_dim = self.latent_dim
        hidden_decoder_dim = self.hidden_decoder_dim
        lam = self.lam
        
        with tf.variable_scope("Input"):
            self.x = tf.placeholder("float32", shape=[None, 1, input_dim])
            self.y_ = tf.placeholder("float32", shape=[None, 1, classes])
            self.keep_prob = tf.placeholder("float")
            
            #GO = tf.fill((tf.shape(self.x)[0], 1), 0.5)
            
            #y_with_GO = tf.stack([self.y_, GO])
            
        with tf.variable_scope("lstm"):
            multi_cell = MultiRNNCell([LSTMCell(input_dim) for i in range(hidden_layers)] )
            
            self.x = tf.unstack(self.x, axis= 1)
            self.y_ = tf.unstack(self.y_, axis = 1)
            self.y, states = basic_rnn_seq2seq(self.x, self.y_, multi_cell)
            #self.y = tf.slice(self.y, [0, 0], [-1,2])
            
            #self.out = tf.squeeze(self.y)
            self.y_ = self.y_[0]
            
            self.y = tf.layers.dense(self.y[0], classes, activation = tf.nn.softmax)
        with tf.variable_scope("Loss"):
            
            self.regularized_loss = tf.losses.mean_squared_error(self.y_, self.y)
            correct_prediction = tf.equal(tf.argmax(self.y_, 1), tf.argmax(self.y, 1))
            self.tf_accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32), name = "Accuracy")

        with tf.variable_scope("Optimizer"):
            learning_rate=1e-2
            optimizer = tf.train.AdamOptimizer(learning_rate)
            gradients, variables = zip(*optimizer.compute_gradients(self.regularized_loss))
            gradients = [
                None if gradient is None else tf.clip_by_value(gradient, -1, 1)
                for gradient in gradients]
            self.train_op = optimizer.apply_gradients(zip(gradients, variables))
            #self.train_op = optimizer.minimize(self.regularized_loss)
            
        # add op for merging summary
        #self.summary_op = tf.summary.merge_all()
        self.pred = tf.argmax(self.y, axis = 1)
        self.actual = tf.argmax(self.y_, axis = 1)

        # add Saver ops
        self.saver = tf.train.Saver()
        

In [8]:
batch_iterations = 200

x_train, x_valid, y_train, y_valid, = ms.train_test_split(preprocess.x_train, 
                                                                          preprocess.y_train, 
                                                                          test_size=0.1)
batch_indices = np.array_split(np.arange(x_train.shape[0]), 
                                           batch_iterations)
                                                                          
for i in batch_indices:
    print(x_train[i,np.newaxis,:])
    print(y_train[i,np.newaxis,:])

[[[-0.11024922 -0.0077544  -0.00488781 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00771114 -0.00364218 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 ..., 
 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00772681 -0.00463963 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]]
[[[0 1]]

 [[0 1]]

 [[1 0]]

 ..., 
 [[1 0]]

 [[0 1]]

 [[1 0]]]
[[[-0.11024922 -0.00772238 -0.00477565 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.0077096  -0.00457994 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 ..., 
 [[-0.11024922 -0.00772664 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776122 -0.00488433 ..., -0.01972622  0.

   -0.04643159]]]
[[[0 1]]

 [[0 1]]

 [[1 0]]

 ..., 
 [[1 0]]

 [[0 1]]

 [[0 1]]]
[[[-0.11024922 -0.0077096  -0.00451653 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00765884 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 ..., 
 [[-0.11024922 -0.00771233 -0.00481619 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00675224 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]]
[[[0 1]]

 [[0 1]]

 [[1 0]]

 ..., 
 [[0 1]]

 [[1 0]]

 [[0 1]]]
[[[-0.11024922 -0.0077297  -0.00443671 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00774963 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 ..., 
 [[-0.10986527 -0.00761932 -0.00483758 ..., -0.01972622  0.8

[[[0 1]]

 [[0 1]]

 [[0 1]]

 ..., 
 [[0 1]]

 [[0 1]]

 [[1 0]]]
[[[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00771931 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]

 ..., 
 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.0062739  -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]]
[[[1 0]]

 [[1 0]]

 [[0 1]]

 ..., 
 [[1 0]]

 [[1 0]]

 [[0 1]]]
[[[-0.11024922 -0.00758644 -0.00491864 ..., -0.01972622  0.82515007
   -0.04643159]]

 [[-0.11024922 -0.00776224 -0.00491864 ..., -0.01972622 -1.21190076
   -0.04643159]]

 [[-0.11024922 -0.00775509 -0.00488184 ..., -0.01972622  0.82515007
   -0.04643159]]

 ..., 
 [[-0.11024922 -0.00772681 -0.00462346 ..., -0.01972622  0.82515007
   -0.0464

In [9]:
import collections

class Train:    
    
    result = namedtuple("score", ['epoch', 'no_of_features','hidden_layers','train_score', 'test_score'])

    predictions = {}

    results = []
    best_acc = 0
    
    def train(epochs, net, h,f):
        batch_iterations = 200
    
        with tf.Session() as sess:
            #summary_writer_train = tf.summary.FileWriter('./logs/kdd/VAE/training', graph=sess.graph)
            #summary_writer_valid = tf.summary.FileWriter('./logs/kdd/VAE/validation')

            sess.run(tf.global_variables_initializer())

            for epoch in range(1, (epochs+1)):
                x_train, x_valid, y_train, y_valid, = ms.train_test_split(preprocess.x_train, 
                                                                          preprocess.y_train, 
                                                                          test_size=0.1)
                batch_indices = np.array_split(np.arange(x_train.shape[0]), 
                                           batch_iterations)
                                                                          
                for i in batch_indices:
                    _, train_loss = sess.run([net.train_op, net.regularized_loss], #net.summary_op
                                                          feed_dict={net.x: x_train[i,np.newaxis,:], 
                                                                     net.y_: y_train[i,np.newaxis,:], 
                                                                     net.keep_prob:1})
                    
                    #summary_writer_train.add_summary(summary_str, epoch)
                    if(train_loss > 1e9):
                        print("Step {} | Training Loss: {:.6f}".format(epoch, train_loss))
                    

                valid_accuracy,valid_loss = sess.run([net.tf_accuracy, net.regularized_loss], #net.summary_op 
                                                      feed_dict={net.x: preprocess.x_valid[:,np.newaxis,:], 
                                                                 net.y_: preprocess.y_valid[:,np.newaxis,:], 
                                                                 net.keep_prob:1})
                #summary_writer_valid.add_summary(summary_str, epoch)

                if epoch % 1 == 0:
                    print("Step {} | Training Loss: {:.6f} | Test Loss: {:.6f} | Test Accuracy: {:.6f}".format(epoch, train_loss, valid_loss, valid_accuracy))

            accuracy, pred_value, actual_value, y_pred = sess.run([net.tf_accuracy, 
                                                           net.pred, 
                                                           net.actual, net.y], 
                                                          feed_dict={net.x: preprocess.x_test[:,np.newaxis,:], 
                                                                     net.y_: preprocess.y_test[:,np.newaxis,:], 
                                                                     net.keep_prob:1})


            print("Accuracy on Test data: {}".format(accuracy))
            
            curr_pred = pd.DataFrame({"Attack_prob":y_pred[:,-2], "Normal_prob":y_pred[:, -1]})
            Train.predictions.update({"{}_{}_{}".format(epochs,f,h):curr_pred})
            
            if accuracy > Train.best_acc:
                Train.best_acc = accuracy
                Train.pred_value = pred_value
                Train.actual_value = actual_value
                Train.best_parameters = "Hidden Layers:{}, Features Count:{}".format(h, f)
                #net.saver.save(sess, "dataset/epochs_{}_hidden layers_{}_features count_{}".format(epochs,h,f))
            Train.results.append(Train.result(epochs, f, h,valid_accuracy, accuracy))
            

In [10]:
import itertools
class Hyperparameters:
#    features_arr = [2, 4, 8, 16, 32, 64, 128, 256]
#    hidden_layers_arr = [2, 4, 6, 10]
    features_arr = [4, 8, 16, 32]
    hidden_layers_arr = [2, 4, 6]

    epochs = [20]
    
    for e, h, f in itertools.product(epochs, hidden_layers_arr, features_arr):
        print("Current Layer Attributes - epochs:{} hidden layers:{} features count:{}".format(e,h,f))
        n = network(2,h,f)
        n.build_layers()
        Train.train(e, n, h,f)
        

Current Layer Attributes - epochs:20 hidden layers:2 features count:4


TypeError: unhashable type: 'list'

In [ ]:
df_results = pd.DataFrame(Train.results)

In [ ]:
df_results.sort_values(by = 'test_score', ascending = False)

In [ ]:
pd.Panel(Train.predictions).to_pickle("dataset/tf_vae_dense_trained_together_nsl_kdd_predictions.pkl")
df_results.to_pickle("dataset/tf_vae_dense_trained_together_nsl_kdd_scores.pkl")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    np.set_printoptions(precision=4)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j].round(4),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

def plot(actual_value, pred_value):
    from sklearn.metrics import confusion_matrix
    cm_2labels = confusion_matrix(y_pred = pred_value, y_true = actual_value)
    plt.figure(figsize=[6,6])
    plot_confusion_matrix(cm_2labels, preprocess.output_columns_2labels, normalize = True,
                         title = Train.best_parameters)

In [ ]:
plot(actual_value = Train.actual_value, pred_value = Train.pred_value)